version: '3.8'
services:
  api:
    image: python:3.11-slim
    container_name: gado_api
    restart: unless-stopped
    working_dir: /app
    ports:
    - 8000:8000
    environment:
      DB_HOST: 167.234.234.124
      DB_PORT: 5432
      DB_NAME: controle_gado
      DB_USER: postgres
      DB_PASSWORD: n8n_postgres_2024
      API_SECRET_KEY: 5f8d9c7b6a4e3d2c1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a
      JWT_SECRET: 9a8b7c6d5e4f3g2h1i0j9k8l7m6n5o4p3q2r1s0t9u8v7w6x5y4z3a2b1c0d9e8f
    volumes:
    - ./api_gado.py:/app/api_gado.py
    - ./requirements.txt:/app/requirements.txt
    networks:
    - gado_network
    command: "sh -c \"pip install --no-cache-dir -r requirements.txt &&\n       uvicorn\
      \ api_gado:app --host 0.0.0.0 --port 8000\"\n"
  nginx:
    image: nginx:alpine
    container_name: gado_nginx
    restart: unless-stopped
    ports:
    - 8080:80
    volumes:
    - ./mobile_app.html:/usr/share/nginx/html/index.html
    - ./manifest.json:/usr/share/nginx/html/manifest.json
    - ./sw.js:/usr/share/nginx/html/sw.js
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./img:/usr/share/nginx/html/img:ro
    depends_on:
    - api
    networks:
    - gado_network
networks:
  gado_network:
    driver: bridge
